# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "cabane"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_cabane_faceTop_Fa0_Ctr0():
	P000 = App.Vector(76.0399, -400.0000, 0)
	P001 = App.Vector(2723.9601, -400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2927.0930, -320.7647, 0)
	P003 = App.Vector(3022.9239, -124.9136, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(3096.4823, 757.7876, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(3097.0292, 799.8301, 0)
	P006 = App.Vector(3091.6928, 841.5361, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(2948.2330, 1558.8348, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(2844.2555, 1732.0026, 0)
	P009 = App.Vector(2654.0588, 1800.0000, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(145.9412, 1800.0000, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(-44.2555, 1732.0026, 0)
	P012 = App.Vector(-148.2330, 1558.8348, 0)
	S007 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(-291.6928, 841.5361, 0)
	S008 = Part.LineSegment(P012, P013)
	P014 = App.Vector(-297.0292, 799.8301, 0)
	P015 = App.Vector(-296.4823, 757.7876, 0)
	S009 = Part.Arc(P013, P014, P015)
	P016 = App.Vector(-222.9239, -124.9136, 0)
	S010 = Part.LineSegment(P015, P016)
	P017 = App.Vector(-127.0930, -320.7647, 0)
	P018 = App.Vector(76.0399, -400.0000, 0)
	S011 = Part.Arc(P016, P017, P018)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceTop_Fa0():
	FC000 = ctr_face_cabane_faceTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceTop():
	FA000 = face_cabane_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceFront_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 440.0000, 0)
	P001 = App.Vector(700.0000, 440.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(521.3178, 1244.0701, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(522.1945, 1334.6148, 0)
	P004 = App.Vector(562.9109, 1415.4931, 0)
	S002 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(823.1596, 1727.7915, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(990.4072, 1799.2915, 0)
	P007 = App.Vector(1146.4035, 1705.7544, 0)
	S004 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(1452.8604, 1215.4234, 0)
	S005 = Part.LineSegment(P007, P008)
	P009 = App.Vector(1481.2998, 1137.3619, 0)
	P010 = App.Vector(1475.5655, 1054.4793, 0)
	S006 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(1300.0000, 440.0000, 0)
	S007 = Part.LineSegment(P010, P011)
	P012 = App.Vector(1600.0000, 440.0000, 0)
	S008 = Part.LineSegment(P011, P012)
	P013 = App.Vector(1700.0000, 1420.2679, 0)
	S009 = Part.LineSegment(P012, P013)
	P014 = App.Vector(800.0000, 2410.2679, 0)
	S010 = Part.LineSegment(P013, P014)
	P015 = App.Vector(800.0000, 2415.9630, 0)
	S011 = Part.LineSegment(P014, P015)
	P016 = App.Vector(-200.0000, 1749.2963, 0)
	S012 = Part.LineSegment(P015, P016)
	P017 = App.Vector(0.0000, 440.0000, 0)
	S013 = Part.LineSegment(P016, P017)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceFront_Fa0():
	FC000 = ctr_face_cabane_faceFaceFront_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceFront():
	FA000 = face_cabane_faceFaceFront_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceBack_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 440.0000, 0)
	P001 = App.Vector(1600.0000, 440.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1700.0000, 1420.2679, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(800.0000, 2410.2679, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(800.0000, 2415.9630, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-200.0000, 1749.2963, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(0.0000, 440.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceBack_Fa0():
	FC000 = ctr_face_cabane_faceFaceBack_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceFaceBack_Fa1_Ctr0():
	P000 = App.Vector(215.3010, 1140.0000, 0)
	P001 = App.Vector(534.0604, 1140.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(589.1095, 1156.5159, 0)
	P003 = App.Vector(625.9749, 1200.6081, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(840.2606, 1700.6081, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(831.8302, 1795.0491, 0)
	P006 = App.Vector(748.3461, 1840.0000, 0)
	S003 = Part.Arc(P004, P005, P006)
	P007 = App.Vector(286.7295, 1840.0000, 0)
	S004 = Part.LineSegment(P006, P007)
	P008 = App.Vector(221.2094, 1815.5454, 0)
	P009 = App.Vector(187.7346, 1754.1421, 0)
	S005 = Part.Arc(P007, P008, P009)
	P010 = App.Vector(116.3060, 1254.1421, 0)
	S006 = Part.LineSegment(P009, P010)
	P011 = App.Vector(139.7556, 1174.4798, 0)
	P012 = App.Vector(215.3010, 1140.0000, 0)
	S007 = Part.Arc(P010, P011, P012)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceBack_Fa1():
	FC000 = ctr_face_cabane_faceFaceBack_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceBack():
	FA000 = face_cabane_faceFaceBack_Fa0()
	FA001 = face_cabane_faceFaceBack_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceRoof_Fa0_Ctr0():
	P000 = App.Vector(800.0000, 2440.0000, 0)
	P001 = App.Vector(-400.0000, 1640.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-388.9060, 1623.3590, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(800.0000, 2415.9630, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(800.0000, 2410.2679, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1785.2012, 1326.5465, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(1800.0000, 1340.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(800.0000, 2440.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceRoof_Fa0():
	FC000 = ctr_face_cabane_faceFaceRoof_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceRoof():
	FA000 = face_cabane_faceFaceRoof_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceFaceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 440.0000, 0)
	P001 = App.Vector(20.2320, 440.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-181.6379, 1761.5377, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-200.0000, 1749.2963, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 440.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceSide_Fa0():
	FC000 = ctr_face_cabane_faceFaceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceFaceSide_Fa1_Ctr0():
	P000 = App.Vector(1600.0000, 440.0000, 0)
	P001 = App.Vector(1700.0000, 1420.2679, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1681.9245, 1440.1509, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1579.8962, 440.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1600.0000, 440.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceFaceSide_Fa1():
	FC000 = ctr_face_cabane_faceFaceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceFaceSide():
	FA000 = face_cabane_faceFaceSide_Fa0()
	FA001 = face_cabane_faceFaceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 440.0000, 0)
	P001 = App.Vector(2600.0000, 440.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 1749.2963, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1749.2963, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 440.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceSide_Fa0():
	FC000 = ctr_face_cabane_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_faceSide_Fa1_Ctr0():
	P000 = App.Vector(-300.0000, 2440.0000, 0)
	P001 = App.Vector(-200.0000, 1640.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(3000.0000, 1640.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(3100.0000, 2440.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-300.0000, 2440.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_faceSide_Fa1():
	FC000 = ctr_face_cabane_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_faceSide():
	FA000 = face_cabane_faceSide_Fa0()
	FA001 = face_cabane_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(2600.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 199.8250, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 199.8250, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0():
	P000 = App.Vector(0.0000, 200.0250, 0)
	P001 = App.Vector(2600.0000, 200.0250, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 399.8500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 399.8500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 200.0250, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0():
	P000 = App.Vector(0.0000, 400.0500, 0)
	P001 = App.Vector(2600.0000, 400.0500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 599.8750, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 599.8750, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 400.0500, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0():
	P000 = App.Vector(0.0000, 600.0750, 0)
	P001 = App.Vector(2600.0000, 600.0750, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 799.9000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 799.9000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 600.0750, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0():
	P000 = App.Vector(0.0000, 800.1000, 0)
	P001 = App.Vector(2600.0000, 800.1000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 999.9250, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 999.9250, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 800.1000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa4():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0():
	P000 = App.Vector(0.0000, 1000.1250, 0)
	P001 = App.Vector(2600.0000, 1000.1250, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 1199.9500, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1199.9500, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1000.1250, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa5():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0():
	P000 = App.Vector(0.0000, 1200.1500, 0)
	P001 = App.Vector(2600.0000, 1200.1500, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 1399.9750, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1399.9750, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1200.1500, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa6():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherTop_Fa7_Ctr0():
	P000 = App.Vector(0.0000, 1400.1750, 0)
	P001 = App.Vector(2600.0000, 1400.1750, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 1400.1750, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherTop_Fa7():
	FC000 = ctr_face_cabane_plancher_facePlancherTop_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherTop():
	FA000 = face_cabane_plancher_facePlancherTop_Fa0()
	FA001 = face_cabane_plancher_facePlancherTop_Fa1()
	FA002 = face_cabane_plancher_facePlancherTop_Fa2()
	FA003 = face_cabane_plancher_facePlancherTop_Fa3()
	FA004 = face_cabane_plancher_facePlancherTop_Fa4()
	FA005 = face_cabane_plancher_facePlancherTop_Fa5()
	FA006 = face_cabane_plancher_facePlancherTop_Fa6()
	FA007 = face_cabane_plancher_facePlancherTop_Fa7()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(199.8154, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(199.8154, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa0():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0():
	P000 = App.Vector(200.0154, 0.0000, 0)
	P001 = App.Vector(399.8308, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(399.8308, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(200.0154, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(200.0154, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa1():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0():
	P000 = App.Vector(400.0308, 0.0000, 0)
	P001 = App.Vector(599.8462, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(599.8462, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(400.0308, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(400.0308, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa2():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0():
	P000 = App.Vector(600.0462, 0.0000, 0)
	P001 = App.Vector(799.8615, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(799.8615, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(600.0462, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(600.0462, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa3():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa4_Ctr0():
	P000 = App.Vector(800.0615, 0.0000, 0)
	P001 = App.Vector(999.8769, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(999.8769, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(800.0615, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(800.0615, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa4():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa4_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa5_Ctr0():
	P000 = App.Vector(1000.0769, 0.0000, 0)
	P001 = App.Vector(1199.8923, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1199.8923, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1000.0769, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1000.0769, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa5():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa5_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa6_Ctr0():
	P000 = App.Vector(1200.0923, 0.0000, 0)
	P001 = App.Vector(1399.9077, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1399.9077, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1200.0923, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1200.0923, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa6():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa6_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa7_Ctr0():
	P000 = App.Vector(1400.1077, 0.0000, 0)
	P001 = App.Vector(1599.9231, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1599.9231, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1400.1077, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1400.1077, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa7():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa7_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa8_Ctr0():
	P000 = App.Vector(1600.1231, 0.0000, 0)
	P001 = App.Vector(1799.9385, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1799.9385, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1600.1231, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1600.1231, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa8():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa8_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa9_Ctr0():
	P000 = App.Vector(1800.1385, 0.0000, 0)
	P001 = App.Vector(1999.9538, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1999.9538, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1800.1385, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1800.1385, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa9():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa9_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa10_Ctr0():
	P000 = App.Vector(2000.1538, 0.0000, 0)
	P001 = App.Vector(2199.9692, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2199.9692, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2000.1538, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2000.1538, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa10():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa10_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa11_Ctr0():
	P000 = App.Vector(2200.1692, 0.0000, 0)
	P001 = App.Vector(2399.9846, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2399.9846, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2200.1692, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2200.1692, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa11():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa11_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_facePlancherBottom_Fa12_Ctr0():
	P000 = App.Vector(2400.1846, 0.0000, 0)
	P001 = App.Vector(2600.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2600.0000, 1600.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2400.1846, 1600.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2400.1846, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_facePlancherBottom_Fa12():
	FC000 = ctr_face_cabane_plancher_facePlancherBottom_Fa12_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_facePlancherBottom():
	FA000 = face_cabane_plancher_facePlancherBottom_Fa0()
	FA001 = face_cabane_plancher_facePlancherBottom_Fa1()
	FA002 = face_cabane_plancher_facePlancherBottom_Fa2()
	FA003 = face_cabane_plancher_facePlancherBottom_Fa3()
	FA004 = face_cabane_plancher_facePlancherBottom_Fa4()
	FA005 = face_cabane_plancher_facePlancherBottom_Fa5()
	FA006 = face_cabane_plancher_facePlancherBottom_Fa6()
	FA007 = face_cabane_plancher_facePlancherBottom_Fa7()
	FA008 = face_cabane_plancher_facePlancherBottom_Fa8()
	FA009 = face_cabane_plancher_facePlancherBottom_Fa9()
	FA010 = face_cabane_plancher_facePlancherBottom_Fa10()
	FA011 = face_cabane_plancher_facePlancherBottom_Fa11()
	FA012 = face_cabane_plancher_facePlancherBottom_Fa12()
	rOneFig = FA000.fuse([FA001, FA002, FA003, FA004, FA005, FA006, FA007, FA008, FA009, FA010, FA011, FA012])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0():
	P000 = App.Vector(80.0000, 400.0000, 0)
	P001 = App.Vector(160.0000, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(160.0000, 325.6713, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(159.0000, 320.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(80.0000, 320.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(80.0000, 400.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa0():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0():
	P000 = App.Vector(1520.0000, 400.0000, 0)
	P001 = App.Vector(1440.0000, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1440.0000, 325.6713, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1441.0000, 320.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1520.0000, 320.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(1520.0000, 400.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceBeam_Fa1():
	FC000 = ctr_face_cabane_plancher_faceBeam_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceBeam():
	FA000 = face_cabane_plancher_faceBeam_Fa0()
	FA001 = face_cabane_plancher_faceBeam_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0():
	P000 = App.Vector(254.3403, 400.0000, 0)
	P001 = App.Vector(173.1062, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(102.5754, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(183.8095, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(254.3403, 400.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa0():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0():
	P000 = App.Vector(1345.6597, 400.0000, 0)
	P001 = App.Vector(1426.8938, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1497.4246, 0.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(1416.1905, 0.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(1345.6597, 400.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceLeg_Fa1():
	FC000 = ctr_face_cabane_plancher_faceLeg_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceLeg():
	FA000 = face_cabane_plancher_faceLeg_Fa0()
	FA001 = face_cabane_plancher_faceLeg_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0():
	P000 = App.Vector(254.3403, 400.0000, 0)
	P001 = App.Vector(1345.6597, 400.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1359.7659, 320.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(240.2341, 320.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(254.3403, 400.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceButtress_Fa0():
	FC000 = ctr_face_cabane_plancher_faceButtress_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceButtress():
	FA000 = face_cabane_plancher_faceButtress_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_cabane_plancher_faceSide_Fa0_Ctr0():
	P000 = App.Vector(160.0000, 0.0000, 0)
	P001 = App.Vector(240.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(240.0000, 400.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(160.0000, 400.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(160.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa0():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_cabane_plancher_faceSide_Fa1_Ctr0():
	P000 = App.Vector(2360.0000, 0.0000, 0)
	P001 = App.Vector(2440.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(2440.0000, 400.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(2360.0000, 400.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(2360.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_cabane_plancher_faceSide_Fa1():
	FC000 = ctr_face_cabane_plancher_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def cabane_plancher_faceSide():
	FA000 = face_cabane_plancher_faceSide_Fa0()
	FA001 = face_cabane_plancher_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_cabane_plancher_plancherTop():
	FIG = cabane_plancher_facePlancherTop()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 420))
	return VFP
subpax_cabane_plancher_plancherTop = fex_subpax_cabane_plancher_plancherTop()

def fex_subpax_cabane_plancher_plancherBottom():
	FIG = cabane_plancher_facePlancherBottom()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 400))
	return VFP
subpax_cabane_plancher_plancherBottom = fex_subpax_cabane_plancher_plancherBottom()

def fex_subpax_cabane_plancher_beam():
	FIG = cabane_plancher_faceBeam()
	VEX = FIG.extrude(App.Vector(0, 0, 2600))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90)
	VFP = VR3.translate(App.Vector(2600, 1600.0000000000002, 0))
	return VFP
subpax_cabane_plancher_beam = fex_subpax_cabane_plancher_beam()

def fex_subpax_cabane_plancher_leg1():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90)
	VFP = VR3.translate(App.Vector(240, 1600, 0))
	return VFP
subpax_cabane_plancher_leg1 = fex_subpax_cabane_plancher_leg1()

def fex_subpax_cabane_plancher_leg2():
	FIG = cabane_plancher_faceLeg()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90)
	VFP = VR3.translate(App.Vector(2440, 1600.0000000000002, 0))
	return VFP
subpax_cabane_plancher_leg2 = fex_subpax_cabane_plancher_leg2()

def fex_subpax_cabane_plancher_buttress1():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90)
	VFP = VR3.translate(App.Vector(240, 1600, 0))
	return VFP
subpax_cabane_plancher_buttress1 = fex_subpax_cabane_plancher_buttress1()

def fex_subpax_cabane_plancher_buttress2():
	FIG = cabane_plancher_faceButtress()
	VEX = FIG.extrude(App.Vector(0, 0, 80))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), -90)
	VFP = VR3.translate(App.Vector(2440, 1600.0000000000002, 0))
	return VFP
subpax_cabane_plancher_buttress2 = fex_subpax_cabane_plancher_buttress2()

pax_cabane_plancher = subpax_cabane_plancher_plancherTop.fuse([subpax_cabane_plancher_plancherBottom, subpax_cabane_plancher_beam, subpax_cabane_plancher_leg1, subpax_cabane_plancher_leg2, subpax_cabane_plancher_buttress1, subpax_cabane_plancher_buttress2])

IVR1_pax_cabane_plancher = pax_cabane_plancher.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
IVR2_pax_cabane_plancher = IVR1_pax_cabane_plancher.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
IVR3_pax_cabane_plancher = IVR2_pax_cabane_plancher.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
inpax_cabane_plancher = IVR3_pax_cabane_plancher.translate(App.Vector(0, 0, 0))

def fex_subpax_cabane_roofTop():
	FIG = cabane_faceTop()
	VEX = FIG.extrude(App.Vector(0, 0, 2440))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_cabane_roofTop = fex_subpax_cabane_roofTop()

def fex_subpax_cabane_roofMax():
	FIG = cabane_faceFaceRoof()
	VEX = FIG.extrude(App.Vector(0, 0, 3400))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90)
	VFP = VR3.translate(App.Vector(-300, 0, 0))
	return VFP
subpax_cabane_roofMax = fex_subpax_cabane_roofMax()

def fex_subpax_cabane_Wfront():
	FIG = cabane_faceFaceFront()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90)
	VFP = VR3.translate(App.Vector(2580, 0, 0))
	return VFP
subpax_cabane_Wfront = fex_subpax_cabane_Wfront()

def fex_subpax_cabane_Wback():
	FIG = cabane_faceFaceBack()
	VEX = FIG.extrude(App.Vector(0, 0, 20))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_cabane_Wback = fex_subpax_cabane_Wback()

def fex_subpax_cabane_Wside():
	FIG = cabane_faceFaceSide()
	VEX = FIG.extrude(App.Vector(0, 0, 2600))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 90)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_cabane_Wside = fex_subpax_cabane_Wside()

ipax_cabane_roof = subpax_cabane_roofMax.common([subpax_cabane_roofTop])
pax_cabane = inpax_cabane_plancher.fuse([ipax_cabane_roof, subpax_cabane_Wfront, subpax_cabane_Wback, subpax_cabane_Wside])

pax_cabane.check()
#pax_cabane.exportBrep(f"{outFileName}.brep")
#pax_cabane.exportIges(f"{outFileName}.igs")
#pax_cabane.exportStep(f"{outFileName}.stp")
pax_cabane.exportStl(f"{outFileName}.stl")

