# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "reinforced_tube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(24.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopExt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopExt():
	FA000 = face_reinforced_tube_faceTopExt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(23.9815, 0.9422, 0)
	P002 = App.Vector(23.9260, 1.8830, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(23.6378, 2.7151, 0)
	P004 = App.Vector(22.9801, 3.3007, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(20.8056, 4.4122, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(20.4198, 4.9024, 0)
	P007 = App.Vector(20.5411, 5.5142, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(21.9739, 7.4918, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(22.2940, 8.3121, 0)
	P010 = App.Vector(22.1731, 9.1844, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.7954, 10.0478, 0)
	P012 = App.Vector(21.3842, 10.8958, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(20.7994, 11.5542, 0)
	P014 = App.Vector(19.9677, 11.8436, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(17.5334, 12.0383, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(16.9894, 12.3435, 0)
	P017 = App.Vector(16.8673, 12.9552, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(17.4343, 15.3306, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(17.4161, 16.2110, 0)
	P020 = App.Vector(16.9706, 16.9706, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(16.2912, 17.6237, 0)
	P022 = App.Vector(15.5868, 18.2497, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(14.7946, 18.6343, 0)
	P024 = App.Vector(13.9154, 18.5833, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(11.5919, 17.8317, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(10.9725, 17.9054, 0)
	P027 = App.Vector(10.6256, 18.4239, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(10.2404, 20.8354, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(9.8867, 21.6418, 0)
	P030 = App.Vector(9.1844, 22.1731, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(8.3068, 22.5166, 0)
	P032 = App.Vector(7.4164, 22.8254, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(6.5373, 22.8775, 0)
	P034 = App.Vector(5.7446, 22.4940, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(3.8856, 20.9104, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(3.2851, 20.7415, 0)
	P037 = App.Vector(2.7662, 21.0877, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(1.4875, 23.1682, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(0.8521, 23.7779, 0)
	P040 = App.Vector(0.0000, 24.0000, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-0.9422, 23.9815, 0)
	P042 = App.Vector(-1.8830, 23.9260, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-2.7151, 23.6378, 0)
	P044 = App.Vector(-3.3007, 22.9801, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-4.4122, 20.8056, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-4.9024, 20.4198, 0)
	P047 = App.Vector(-5.5142, 20.5411, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-7.4918, 21.9739, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-8.3121, 22.2940, 0)
	P050 = App.Vector(-9.1844, 22.1731, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-10.0478, 21.7954, 0)
	P052 = App.Vector(-10.8958, 21.3842, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-11.5542, 20.7994, 0)
	P054 = App.Vector(-11.8436, 19.9677, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-12.0383, 17.5334, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-12.3435, 16.9894, 0)
	P057 = App.Vector(-12.9552, 16.8673, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-15.3306, 17.4343, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-16.2110, 17.4161, 0)
	P060 = App.Vector(-16.9706, 16.9706, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-17.6237, 16.2912, 0)
	P062 = App.Vector(-18.2497, 15.5868, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-18.6343, 14.7946, 0)
	P064 = App.Vector(-18.5833, 13.9154, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-17.8317, 11.5919, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-17.9054, 10.9725, 0)
	P067 = App.Vector(-18.4239, 10.6256, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-20.8354, 10.2404, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-21.6418, 9.8867, 0)
	P070 = App.Vector(-22.1731, 9.1844, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-22.5166, 8.3068, 0)
	P072 = App.Vector(-22.8254, 7.4164, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-22.8775, 6.5373, 0)
	P074 = App.Vector(-22.4940, 5.7446, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-20.9104, 3.8856, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-20.7415, 3.2851, 0)
	P077 = App.Vector(-21.0877, 2.7662, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-23.1682, 1.4875, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-23.7779, 0.8521, 0)
	P080 = App.Vector(-24.0000, 0.0000, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-23.9815, -0.9422, 0)
	P082 = App.Vector(-23.9260, -1.8830, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-23.6378, -2.7151, 0)
	P084 = App.Vector(-22.9801, -3.3007, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-20.8056, -4.4122, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-20.4198, -4.9024, 0)
	P087 = App.Vector(-20.5411, -5.5142, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-21.9739, -7.4918, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-22.2940, -8.3121, 0)
	P090 = App.Vector(-22.1731, -9.1844, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-21.7954, -10.0478, 0)
	P092 = App.Vector(-21.3842, -10.8958, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-20.7994, -11.5542, 0)
	P094 = App.Vector(-19.9677, -11.8436, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-17.5334, -12.0383, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-16.9894, -12.3435, 0)
	P097 = App.Vector(-16.8673, -12.9552, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-17.4343, -15.3306, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-17.4161, -16.2110, 0)
	P100 = App.Vector(-16.9706, -16.9706, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-16.2912, -17.6237, 0)
	P102 = App.Vector(-15.5868, -18.2497, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-14.7946, -18.6343, 0)
	P104 = App.Vector(-13.9154, -18.5833, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-11.5919, -17.8317, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(-10.9725, -17.9054, 0)
	P107 = App.Vector(-10.6256, -18.4239, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(-10.2404, -20.8354, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(-9.8867, -21.6418, 0)
	P110 = App.Vector(-9.1844, -22.1731, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(-8.3068, -22.5166, 0)
	P112 = App.Vector(-7.4164, -22.8254, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(-6.5373, -22.8775, 0)
	P114 = App.Vector(-5.7446, -22.4940, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-3.8856, -20.9104, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(-3.2851, -20.7415, 0)
	P117 = App.Vector(-2.7662, -21.0877, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(-1.4875, -23.1682, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(-0.8521, -23.7779, 0)
	P120 = App.Vector(-0.0000, -24.0000, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(0.9422, -23.9815, 0)
	P122 = App.Vector(1.8830, -23.9260, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(2.7151, -23.6378, 0)
	P124 = App.Vector(3.3007, -22.9801, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(4.4122, -20.8056, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(4.9024, -20.4198, 0)
	P127 = App.Vector(5.5142, -20.5411, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(7.4918, -21.9739, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(8.3121, -22.2940, 0)
	P130 = App.Vector(9.1844, -22.1731, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(10.0478, -21.7954, 0)
	P132 = App.Vector(10.8958, -21.3842, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(11.5542, -20.7994, 0)
	P134 = App.Vector(11.8436, -19.9677, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(12.0383, -17.5334, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(12.3435, -16.9894, 0)
	P137 = App.Vector(12.9552, -16.8673, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(15.3306, -17.4343, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(16.2110, -17.4161, 0)
	P140 = App.Vector(16.9706, -16.9706, 0)
	S083 = Part.Arc(P138, P139, P140)
	P141 = App.Vector(17.6237, -16.2912, 0)
	P142 = App.Vector(18.2497, -15.5868, 0)
	S084 = Part.Arc(P140, P141, P142)
	P143 = App.Vector(18.6343, -14.7946, 0)
	P144 = App.Vector(18.5833, -13.9154, 0)
	S085 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(17.8317, -11.5919, 0)
	S086 = Part.LineSegment(P144, P145)
	P146 = App.Vector(17.9054, -10.9725, 0)
	P147 = App.Vector(18.4239, -10.6256, 0)
	S087 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(20.8354, -10.2404, 0)
	S088 = Part.LineSegment(P147, P148)
	P149 = App.Vector(21.6418, -9.8867, 0)
	P150 = App.Vector(22.1731, -9.1844, 0)
	S089 = Part.Arc(P148, P149, P150)
	P151 = App.Vector(22.5166, -8.3068, 0)
	P152 = App.Vector(22.8254, -7.4164, 0)
	S090 = Part.Arc(P150, P151, P152)
	P153 = App.Vector(22.8775, -6.5373, 0)
	P154 = App.Vector(22.4940, -5.7446, 0)
	S091 = Part.Arc(P152, P153, P154)
	P155 = App.Vector(20.9104, -3.8856, 0)
	S092 = Part.LineSegment(P154, P155)
	P156 = App.Vector(20.7415, -3.2851, 0)
	P157 = App.Vector(21.0877, -2.7662, 0)
	S093 = Part.Arc(P155, P156, P157)
	P158 = App.Vector(23.1682, -1.4875, 0)
	S094 = Part.LineSegment(P157, P158)
	P159 = App.Vector(23.7779, -0.8521, 0)
	P160 = App.Vector(24.0000, -0.0000, 0)
	S095 = Part.Arc(P158, P159, P160)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1():
	P000 = App.Vector(23.0000, 0.0000, 0)
	P001 = App.Vector(22.9823, 0.9030, 0)
	P002 = App.Vector(22.9291, 1.8046, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(22.8059, 2.1601, 0)
	P004 = App.Vector(22.5249, 2.4103, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(20.3505, 3.5218, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(19.4474, 4.6689, 0)
	P007 = App.Vector(19.7313, 6.1009, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(21.1641, 8.0785, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(21.3009, 8.4290, 0)
	P010 = App.Vector(21.2492, 8.8017, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.8873, 9.6292, 0)
	P012 = App.Vector(20.4932, 10.4418, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(20.2433, 10.7231, 0)
	P014 = App.Vector(19.8879, 10.8467, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(17.4536, 11.0415, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(16.1803, 11.7557, 0)
	P017 = App.Vector(15.8946, 13.1874, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(16.4616, 15.5627, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(16.4538, 15.9389, 0)
	P020 = App.Vector(16.2635, 16.2635, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(15.6124, 16.8894, 0)
	P022 = App.Vector(14.9373, 17.4893, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(14.5988, 17.6537, 0)
	P024 = App.Vector(14.2232, 17.6319, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(11.8996, 16.8803, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(10.4500, 17.0528, 0)
	P027 = App.Vector(9.6381, 18.2661, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(9.2529, 20.6777, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(9.1018, 21.0222, 0)
	P030 = App.Vector(8.8017, 21.2492, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(7.9607, 21.5784, 0)
	P032 = App.Vector(7.1074, 21.8743, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(6.7318, 21.8966, 0)
	P034 = App.Vector(6.3931, 21.7327, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(4.5340, 20.1491, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(3.1287, 19.7538, 0)
	P037 = App.Vector(1.9143, 20.5641, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(0.6356, 22.6446, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(0.3641, 22.9051, 0)
	P040 = App.Vector(0.0000, 23.0000, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-0.9030, 22.9823, 0)
	P042 = App.Vector(-1.8046, 22.9291, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-2.1601, 22.8059, 0)
	P044 = App.Vector(-2.4103, 22.5249, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-3.5218, 20.3505, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-4.6689, 19.4474, 0)
	P047 = App.Vector(-6.1009, 19.7313, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-8.0785, 21.1641, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-8.4290, 21.3009, 0)
	P050 = App.Vector(-8.8017, 21.2492, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-9.6292, 20.8873, 0)
	P052 = App.Vector(-10.4418, 20.4932, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-10.7231, 20.2433, 0)
	P054 = App.Vector(-10.8467, 19.8879, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-11.0415, 17.4536, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-11.7557, 16.1803, 0)
	P057 = App.Vector(-13.1874, 15.8946, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-15.5627, 16.4616, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-15.9389, 16.4538, 0)
	P060 = App.Vector(-16.2635, 16.2635, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-16.8894, 15.6124, 0)
	P062 = App.Vector(-17.4893, 14.9373, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-17.6537, 14.5988, 0)
	P064 = App.Vector(-17.6319, 14.2232, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-16.8803, 11.8996, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-17.0528, 10.4500, 0)
	P067 = App.Vector(-18.2661, 9.6381, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-20.6777, 9.2529, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-21.0222, 9.1018, 0)
	P070 = App.Vector(-21.2492, 8.8017, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-21.5784, 7.9607, 0)
	P072 = App.Vector(-21.8743, 7.1074, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-21.8966, 6.7318, 0)
	P074 = App.Vector(-21.7327, 6.3931, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-20.1491, 4.5340, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-19.7538, 3.1287, 0)
	P077 = App.Vector(-20.5641, 1.9143, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-22.6446, 0.6356, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-22.9051, 0.3641, 0)
	P080 = App.Vector(-23.0000, 0.0000, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-22.9823, -0.9030, 0)
	P082 = App.Vector(-22.9291, -1.8046, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-22.8059, -2.1601, 0)
	P084 = App.Vector(-22.5249, -2.4103, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-20.3505, -3.5218, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-19.4474, -4.6689, 0)
	P087 = App.Vector(-19.7313, -6.1009, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-21.1641, -8.0785, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-21.3009, -8.4290, 0)
	P090 = App.Vector(-21.2492, -8.8017, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-20.8873, -9.6292, 0)
	P092 = App.Vector(-20.4932, -10.4418, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-20.2433, -10.7231, 0)
	P094 = App.Vector(-19.8879, -10.8467, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-17.4536, -11.0415, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-16.1803, -11.7557, 0)
	P097 = App.Vector(-15.8946, -13.1874, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-16.4616, -15.5627, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-16.4538, -15.9389, 0)
	P100 = App.Vector(-16.2635, -16.2635, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-15.6124, -16.8894, 0)
	P102 = App.Vector(-14.9373, -17.4893, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-14.5988, -17.6537, 0)
	P104 = App.Vector(-14.2232, -17.6319, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-11.8996, -16.8803, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(-10.4500, -17.0528, 0)
	P107 = App.Vector(-9.6381, -18.2661, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(-9.2529, -20.6777, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(-9.1018, -21.0222, 0)
	P110 = App.Vector(-8.8017, -21.2492, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(-7.9607, -21.5784, 0)
	P112 = App.Vector(-7.1074, -21.8743, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(-6.7318, -21.8966, 0)
	P114 = App.Vector(-6.3931, -21.7327, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-4.5340, -20.1491, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(-3.1287, -19.7538, 0)
	P117 = App.Vector(-1.9143, -20.5641, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(-0.6356, -22.6446, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(-0.3641, -22.9051, 0)
	P120 = App.Vector(-0.0000, -23.0000, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(0.9030, -22.9823, 0)
	P122 = App.Vector(1.8046, -22.9291, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(2.1601, -22.8059, 0)
	P124 = App.Vector(2.4103, -22.5249, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(3.5218, -20.3505, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(4.6689, -19.4474, 0)
	P127 = App.Vector(6.1009, -19.7313, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(8.0785, -21.1641, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(8.4290, -21.3009, 0)
	P130 = App.Vector(8.8017, -21.2492, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(9.6292, -20.8873, 0)
	P132 = App.Vector(10.4418, -20.4932, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(10.7231, -20.2433, 0)
	P134 = App.Vector(10.8467, -19.8879, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(11.0415, -17.4536, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(11.7557, -16.1803, 0)
	P137 = App.Vector(13.1874, -15.8946, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(15.5627, -16.4616, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(15.9389, -16.4538, 0)
	P140 = App.Vector(16.2635, -16.2635, 0)
	S083 = Part.Arc(P138, P139, P140)
	P141 = App.Vector(16.8894, -15.6124, 0)
	P142 = App.Vector(17.4893, -14.9373, 0)
	S084 = Part.Arc(P140, P141, P142)
	P143 = App.Vector(17.6537, -14.5988, 0)
	P144 = App.Vector(17.6319, -14.2232, 0)
	S085 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(16.8803, -11.8996, 0)
	S086 = Part.LineSegment(P144, P145)
	P146 = App.Vector(17.0528, -10.4500, 0)
	P147 = App.Vector(18.2661, -9.6381, 0)
	S087 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(20.6777, -9.2529, 0)
	S088 = Part.LineSegment(P147, P148)
	P149 = App.Vector(21.0222, -9.1018, 0)
	P150 = App.Vector(21.2492, -8.8017, 0)
	S089 = Part.Arc(P148, P149, P150)
	P151 = App.Vector(21.5784, -7.9607, 0)
	P152 = App.Vector(21.8743, -7.1074, 0)
	S090 = Part.Arc(P150, P151, P152)
	P153 = App.Vector(21.8966, -6.7318, 0)
	P154 = App.Vector(21.7327, -6.3931, 0)
	S091 = Part.Arc(P152, P153, P154)
	P155 = App.Vector(20.1491, -4.5340, 0)
	S092 = Part.LineSegment(P154, P155)
	P156 = App.Vector(19.7538, -3.1287, 0)
	P157 = App.Vector(20.5641, -1.9143, 0)
	S093 = Part.Arc(P155, P156, P157)
	P158 = App.Vector(22.6446, -0.6356, 0)
	S094 = Part.LineSegment(P157, P158)
	P159 = App.Vector(22.9051, -0.3641, 0)
	P160 = App.Vector(23.0000, -0.0000, 0)
	S095 = Part.Arc(P158, P159, P160)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceTopWave_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopWave():
	FA000 = face_reinforced_tube_faceTopWave_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(19.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopInt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopInt():
	FA000 = face_reinforced_tube_faceTopInt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-25.0000, 0.0000, 0)
	P001 = App.Vector(-24.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-24.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-25.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa0():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa1_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(25.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(24.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(24.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa1():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa2_Ctr0():
	P000 = App.Vector(-20.0000, 0.0000, 0)
	P001 = App.Vector(-19.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-19.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-20.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-20.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa2():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa3_Ctr0():
	P000 = App.Vector(19.0000, 0.0000, 0)
	P001 = App.Vector(20.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(20.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(19.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(19.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa3():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceSide():
	FA000 = face_reinforced_tube_faceSide_Fa0()
	FA001 = face_reinforced_tube_faceSide_Fa1()
	FA002 = face_reinforced_tube_faceSide_Fa2()
	FA003 = face_reinforced_tube_faceSide_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def fex_subpax_reinforced_tube_topExt():
	FIG = reinforced_tube_faceTopExt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topExt = fex_subpax_reinforced_tube_topExt()

def fex_subpax_reinforced_tube_topWave():
	FIG = reinforced_tube_faceTopWave()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topWave = fex_subpax_reinforced_tube_topWave()

def fex_subpax_reinforced_tube_topInt():
	FIG = reinforced_tube_faceTopInt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topInt = fex_subpax_reinforced_tube_topInt()

pax_reinforced_tube = subpax_reinforced_tube_topExt.fuse([subpax_reinforced_tube_topWave, subpax_reinforced_tube_topInt])

pax_reinforced_tube.check()
#pax_reinforced_tube.exportBrep(f"{outFileName}.brep")
#pax_reinforced_tube.exportIges(f"{outFileName}.igs")
#pax_reinforced_tube.exportStep(f"{outFileName}.stp")
pax_reinforced_tube.exportStl(f"{outFileName}.stl")

