# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "reinforced_tube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(24.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopExt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopExt():
	FA000 = face_reinforced_tube_faceTopExt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0():
	P000 = App.Vector(23.0000, 0.0000, 0)
	P001 = App.Vector(22.7168, 3.5980, 0)
	P002 = App.Vector(21.8743, 7.1074, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(21.5020, 7.5423, 0)
	P004 = App.Vector(20.9312, 7.5854, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(14.5765, 5.4903, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(12.4741, 6.3559, 0)
	P007 = App.Vector(13.0096, 8.5655, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(18.4397, 12.4751, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(18.7404, 12.9623, 0)
	P010 = App.Vector(18.6074, 13.5191, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(16.2635, 16.2635, 0)
	P012 = App.Vector(13.5191, 18.6074, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(12.9623, 18.7404, 0)
	P014 = App.Vector(12.4751, 18.4397, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(8.5655, 13.0096, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(6.3559, 12.4741, 0)
	P017 = App.Vector(5.4903, 14.5765, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(7.5854, 20.9312, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(7.5423, 21.5020, 0)
	P020 = App.Vector(7.1074, 21.8743, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(3.5980, 22.7168, 0)
	P022 = App.Vector(0.0000, 23.0000, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-0.5287, 22.7804, 0)
	P024 = App.Vector(-0.7460, 22.2508, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-0.7172, 15.5597, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-2.1901, 13.8276, 0)
	P027 = App.Vector(-4.1261, 15.0198, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-6.1664, 21.3923, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-6.5367, 21.8288, 0)
	P030 = App.Vector(-7.1074, 21.8743, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-10.4418, 20.4932, 0)
	P032 = App.Vector(-13.5191, 18.6074, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-13.8176, 18.1190, 0)
	P034 = App.Vector(-13.6822, 17.5627, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-9.7260, 12.1665, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-9.8995, 9.8995, 0)
	P037 = App.Vector(-12.1665, 9.7260, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-17.5627, 13.6822, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-18.1190, 13.8176, 0)
	P040 = App.Vector(-18.6074, 13.5191, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-20.4932, 10.4418, 0)
	P042 = App.Vector(-21.8743, 7.1074, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-21.8288, 6.5367, 0)
	P044 = App.Vector(-21.3923, 6.1664, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-15.0198, 4.1261, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-13.8276, 2.1901, 0)
	P047 = App.Vector(-15.5597, 0.7172, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-22.2508, 0.7460, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-22.7804, 0.5287, 0)
	P050 = App.Vector(-23.0000, 0.0000, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-22.7168, -3.5980, 0)
	P052 = App.Vector(-21.8743, -7.1074, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-21.5020, -7.5423, 0)
	P054 = App.Vector(-20.9312, -7.5854, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-14.5765, -5.4903, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-12.4741, -6.3559, 0)
	P057 = App.Vector(-13.0096, -8.5655, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-18.4397, -12.4751, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-18.7404, -12.9623, 0)
	P060 = App.Vector(-18.6074, -13.5191, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-16.2635, -16.2635, 0)
	P062 = App.Vector(-13.5191, -18.6074, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-12.9623, -18.7404, 0)
	P064 = App.Vector(-12.4751, -18.4397, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-8.5655, -13.0096, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-6.3559, -12.4741, 0)
	P067 = App.Vector(-5.4903, -14.5765, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-7.5854, -20.9312, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-7.5423, -21.5020, 0)
	P070 = App.Vector(-7.1074, -21.8743, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-3.5980, -22.7168, 0)
	P072 = App.Vector(-0.0000, -23.0000, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(0.5287, -22.7804, 0)
	P074 = App.Vector(0.7460, -22.2508, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(0.7172, -15.5597, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(2.1901, -13.8276, 0)
	P077 = App.Vector(4.1261, -15.0198, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(6.1664, -21.3923, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(6.5367, -21.8288, 0)
	P080 = App.Vector(7.1074, -21.8743, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(10.4418, -20.4932, 0)
	P082 = App.Vector(13.5191, -18.6074, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(13.8176, -18.1190, 0)
	P084 = App.Vector(13.6822, -17.5627, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(9.7260, -12.1665, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(9.8995, -9.8995, 0)
	P087 = App.Vector(12.1665, -9.7260, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(17.5627, -13.6822, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(18.1190, -13.8176, 0)
	P090 = App.Vector(18.6074, -13.5191, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(20.4932, -10.4418, 0)
	P092 = App.Vector(21.8743, -7.1074, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(21.8288, -6.5367, 0)
	P094 = App.Vector(21.3923, -6.1664, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(15.0198, -4.1261, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(13.8276, -2.1901, 0)
	P097 = App.Vector(15.5597, -0.7172, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(22.2508, -0.7460, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(22.7804, -0.5287, 0)
	P100 = App.Vector(23.0000, -0.0000, 0)
	S059 = Part.Arc(P098, P099, P100)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(23.7045, 3.7544, 0)
	P002 = App.Vector(22.8254, 7.4164, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(21.9541, 8.4343, 0)
	P004 = App.Vector(20.6181, 8.5351, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(14.2634, 6.4400, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(13.3651, 6.8099, 0)
	P007 = App.Vector(13.5939, 7.7540, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(19.0240, 11.6636, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(19.7278, 12.8037, 0)
	P010 = App.Vector(19.4164, 14.1068, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(16.9706, 16.9706, 0)
	P012 = App.Vector(14.1068, 19.4164, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(12.8037, 19.7278, 0)
	P014 = App.Vector(11.6636, 19.0240, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(7.7540, 13.5939, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(6.8099, 13.3651, 0)
	P017 = App.Vector(6.4400, 14.2634, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(8.5351, 20.6181, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(8.4343, 21.9541, 0)
	P020 = App.Vector(7.4164, 22.8254, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(3.7544, 23.7045, 0)
	P022 = App.Vector(0.0000, 24.0000, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(-1.2373, 23.4859, 0)
	P024 = App.Vector(-1.7460, 22.2465, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(-1.7172, 15.5554, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(-2.3465, 14.8153, 0)
	P027 = App.Vector(-3.1737, 15.3247, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(-5.2140, 21.6972, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(-6.0808, 22.7188, 0)
	P030 = App.Vector(-7.4164, 22.8254, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(-10.8958, 21.3842, 0)
	P032 = App.Vector(-14.1068, 19.4164, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(-14.8057, 18.2733, 0)
	P034 = App.Vector(-14.4887, 16.9715, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(-10.5325, 11.5752, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-10.6066, 10.6066, 0)
	P037 = App.Vector(-11.5752, 10.5325, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-16.9715, 14.4887, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-18.2733, 14.8057, 0)
	P040 = App.Vector(-19.4164, 14.1068, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-21.3842, 10.8958, 0)
	P042 = App.Vector(-22.8254, 7.4164, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-22.7188, 6.0808, 0)
	P044 = App.Vector(-21.6972, 5.2140, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-15.3247, 3.1737, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-14.8153, 2.3465, 0)
	P047 = App.Vector(-15.5554, 1.7172, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-22.2465, 1.7460, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-23.4859, 1.2373, 0)
	P050 = App.Vector(-24.0000, 0.0000, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-23.7045, -3.7544, 0)
	P052 = App.Vector(-22.8254, -7.4164, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-21.9541, -8.4343, 0)
	P054 = App.Vector(-20.6181, -8.5351, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-14.2634, -6.4400, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-13.3651, -6.8099, 0)
	P057 = App.Vector(-13.5939, -7.7540, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-19.0240, -11.6636, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-19.7278, -12.8037, 0)
	P060 = App.Vector(-19.4164, -14.1068, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-16.9706, -16.9706, 0)
	P062 = App.Vector(-14.1068, -19.4164, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-12.8037, -19.7278, 0)
	P064 = App.Vector(-11.6636, -19.0240, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-7.7540, -13.5939, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-6.8099, -13.3651, 0)
	P067 = App.Vector(-6.4400, -14.2634, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-8.5351, -20.6181, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-8.4343, -21.9541, 0)
	P070 = App.Vector(-7.4164, -22.8254, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-3.7544, -23.7045, 0)
	P072 = App.Vector(-0.0000, -24.0000, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(1.2373, -23.4859, 0)
	P074 = App.Vector(1.7460, -22.2465, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(1.7172, -15.5554, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(2.3465, -14.8153, 0)
	P077 = App.Vector(3.1737, -15.3247, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(5.2140, -21.6972, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(6.0808, -22.7188, 0)
	P080 = App.Vector(7.4164, -22.8254, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(10.8958, -21.3842, 0)
	P082 = App.Vector(14.1068, -19.4164, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(14.8057, -18.2733, 0)
	P084 = App.Vector(14.4887, -16.9715, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(10.5325, -11.5752, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(10.6066, -10.6066, 0)
	P087 = App.Vector(11.5752, -10.5325, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(16.9715, -14.4887, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(18.2733, -14.8057, 0)
	P090 = App.Vector(19.4164, -14.1068, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(21.3842, -10.8958, 0)
	P092 = App.Vector(22.8254, -7.4164, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(22.7188, -6.0808, 0)
	P094 = App.Vector(21.6972, -5.2140, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(15.3247, -3.1737, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(14.8153, -2.3465, 0)
	P097 = App.Vector(15.5554, -1.7172, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(22.2465, -1.7460, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(23.4859, -1.2373, 0)
	P100 = App.Vector(24.0000, -0.0000, 0)
	S059 = Part.Arc(P098, P099, P100)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceTopWave_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopWave():
	FA000 = face_reinforced_tube_faceTopWave_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def reinforced_tube_faceTopInt():
	rOneFig = undefined
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-25.0000, 0.0000, 0)
	P001 = App.Vector(-24.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-24.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-25.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa0():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa1_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(25.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(24.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(24.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa1():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceSide():
	FA000 = face_reinforced_tube_faceSide_Fa0()
	FA001 = face_reinforced_tube_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_reinforced_tube_topExt():
	FIG = reinforced_tube_faceTopExt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topExt = fex_subpax_reinforced_tube_topExt()

def fex_subpax_reinforced_tube_topWave():
	FIG = reinforced_tube_faceTopWave()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topWave = fex_subpax_reinforced_tube_topWave()

pax_reinforced_tube = subpax_reinforced_tube_topExt.fuse([subpax_reinforced_tube_topWave])

pax_reinforced_tube.check()
#pax_reinforced_tube.exportBrep(f"{outFileName}.brep")
#pax_reinforced_tube.exportIges(f"{outFileName}.igs")
#pax_reinforced_tube.exportStep(f"{outFileName}.stp")
pax_reinforced_tube.exportStl(f"{outFileName}.stl")

