# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "reinforced_tube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(24.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopExt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopExt():
	FA000 = face_reinforced_tube_faceTopExt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0():
	P000 = App.Vector(23.0000, 0.0000, 0)
	P001 = App.Vector(22.9946, 0.5000, 0)
	P002 = App.Vector(22.9783, 0.9998, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(22.9262, 1.2011, 0)
	P004 = App.Vector(22.7968, 1.3638, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(21.3608, 2.5480, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(20.6651, 3.7352, 0)
	P007 = App.Vector(20.9012, 5.0910, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(21.8318, 6.7029, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(21.8960, 6.9006, 0)
	P010 = App.Vector(21.8743, 7.1074, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.7146, 7.5812, 0)
	P012 = App.Vector(21.5447, 8.0515, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(21.4330, 8.2269, 0)
	P014 = App.Vector(21.2596, 8.3416, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(19.5280, 9.0241, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(18.4995, 9.9383, 0)
	P017 = App.Vector(18.3050, 11.3006, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(18.6920, 13.1212, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(18.6920, 13.3291, 0)
	P020 = App.Vector(18.6074, 13.5191, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(18.3091, 13.9204, 0)
	P022 = App.Vector(18.0022, 14.3151, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(17.8418, 14.4474, 0)
	P024 = App.Vector(17.6414, 14.5030, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(15.7836, 14.6169, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(14.5229, 15.1685, 0)
	P027 = App.Vector(13.9170, 16.4041, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(13.7224, 18.2552, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(13.6582, 18.4529, 0)
	P030 = App.Vector(13.5191, 18.6074, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(13.1114, 18.8969, 0)
	P032 = App.Vector(12.6975, 19.1774, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(12.5040, 19.2537, 0)
	P034 = App.Vector(12.2963, 19.2446, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(10.4942, 18.7789, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(9.1248, 18.9140, 0)
	P037 = App.Vector(8.1667, 19.9018, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(7.4097, 21.6021, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(7.2874, 21.7703, 0)
	P040 = App.Vector(7.1074, 21.8743, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(6.6302, 22.0236, 0)
	P042 = App.Vector(6.1498, 22.1626, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(5.9423, 22.1753, 0)
	P044 = App.Vector(5.7476, 22.1025, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(4.1776, 21.1027, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(2.8334, 20.8080, 0)
	P047 = App.Vector(1.6170, 21.4514, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(0.3716, 22.8346, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(0.2034, 22.9568, 0)
	P050 = App.Vector(0.0000, 23.0000, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-0.5000, 22.9946, 0)
	P052 = App.Vector(-0.9998, 22.9783, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-1.2011, 22.9262, 0)
	P054 = App.Vector(-1.3638, 22.7968, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-2.5480, 21.3608, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-3.7352, 20.6651, 0)
	P057 = App.Vector(-5.0910, 20.9012, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.7029, 21.8318, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-6.9006, 21.8960, 0)
	P060 = App.Vector(-7.1074, 21.8743, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.5812, 21.7146, 0)
	P062 = App.Vector(-8.0515, 21.5447, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-8.2269, 21.4330, 0)
	P064 = App.Vector(-8.3416, 21.2596, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-9.0241, 19.5280, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-9.9383, 18.4995, 0)
	P067 = App.Vector(-11.3006, 18.3050, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-13.1212, 18.6920, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-13.3291, 18.6920, 0)
	P070 = App.Vector(-13.5191, 18.6074, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-13.9204, 18.3091, 0)
	P072 = App.Vector(-14.3151, 18.0022, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-14.4474, 17.8418, 0)
	P074 = App.Vector(-14.5030, 17.6414, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-14.6169, 15.7836, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-15.1685, 14.5229, 0)
	P077 = App.Vector(-16.4041, 13.9170, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-18.2552, 13.7224, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-18.4529, 13.6582, 0)
	P080 = App.Vector(-18.6074, 13.5191, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-18.8969, 13.1114, 0)
	P082 = App.Vector(-19.1774, 12.6975, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-19.2537, 12.5040, 0)
	P084 = App.Vector(-19.2446, 12.2963, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-18.7789, 10.4942, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-18.9140, 9.1248, 0)
	P087 = App.Vector(-19.9018, 8.1667, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-21.6021, 7.4097, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-21.7703, 7.2874, 0)
	P090 = App.Vector(-21.8743, 7.1074, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-22.0236, 6.6302, 0)
	P092 = App.Vector(-22.1626, 6.1498, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-22.1753, 5.9423, 0)
	P094 = App.Vector(-22.1025, 5.7476, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-21.1027, 4.1776, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-20.8080, 2.8334, 0)
	P097 = App.Vector(-21.4514, 1.6170, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-22.8346, 0.3716, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-22.9568, 0.2034, 0)
	P100 = App.Vector(-23.0000, 0.0000, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-22.9946, -0.5000, 0)
	P102 = App.Vector(-22.9783, -0.9998, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-22.9262, -1.2011, 0)
	P104 = App.Vector(-22.7968, -1.3638, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-21.3608, -2.5480, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(-20.6651, -3.7352, 0)
	P107 = App.Vector(-20.9012, -5.0910, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(-21.8318, -6.7029, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(-21.8960, -6.9006, 0)
	P110 = App.Vector(-21.8743, -7.1074, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(-21.7146, -7.5812, 0)
	P112 = App.Vector(-21.5447, -8.0515, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(-21.4330, -8.2269, 0)
	P114 = App.Vector(-21.2596, -8.3416, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-19.5280, -9.0241, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(-18.4995, -9.9383, 0)
	P117 = App.Vector(-18.3050, -11.3006, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(-18.6920, -13.1212, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(-18.6920, -13.3291, 0)
	P120 = App.Vector(-18.6074, -13.5191, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(-18.3091, -13.9204, 0)
	P122 = App.Vector(-18.0022, -14.3151, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(-17.8418, -14.4474, 0)
	P124 = App.Vector(-17.6414, -14.5030, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(-15.7836, -14.6169, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(-14.5229, -15.1685, 0)
	P127 = App.Vector(-13.9170, -16.4041, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(-13.7224, -18.2552, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(-13.6582, -18.4529, 0)
	P130 = App.Vector(-13.5191, -18.6074, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(-13.1114, -18.8969, 0)
	P132 = App.Vector(-12.6975, -19.1774, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(-12.5040, -19.2537, 0)
	P134 = App.Vector(-12.2963, -19.2446, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(-10.4942, -18.7789, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(-9.1248, -18.9140, 0)
	P137 = App.Vector(-8.1667, -19.9018, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(-7.4097, -21.6021, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(-7.2874, -21.7703, 0)
	P140 = App.Vector(-7.1074, -21.8743, 0)
	S083 = Part.Arc(P138, P139, P140)
	P141 = App.Vector(-6.6302, -22.0236, 0)
	P142 = App.Vector(-6.1498, -22.1626, 0)
	S084 = Part.Arc(P140, P141, P142)
	P143 = App.Vector(-5.9423, -22.1753, 0)
	P144 = App.Vector(-5.7476, -22.1025, 0)
	S085 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(-4.1776, -21.1027, 0)
	S086 = Part.LineSegment(P144, P145)
	P146 = App.Vector(-2.8334, -20.8080, 0)
	P147 = App.Vector(-1.6170, -21.4514, 0)
	S087 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(-0.3716, -22.8346, 0)
	S088 = Part.LineSegment(P147, P148)
	P149 = App.Vector(-0.2034, -22.9568, 0)
	P150 = App.Vector(-0.0000, -23.0000, 0)
	S089 = Part.Arc(P148, P149, P150)
	P151 = App.Vector(0.5000, -22.9946, 0)
	P152 = App.Vector(0.9998, -22.9783, 0)
	S090 = Part.Arc(P150, P151, P152)
	P153 = App.Vector(1.2011, -22.9262, 0)
	P154 = App.Vector(1.3638, -22.7968, 0)
	S091 = Part.Arc(P152, P153, P154)
	P155 = App.Vector(2.5480, -21.3608, 0)
	S092 = Part.LineSegment(P154, P155)
	P156 = App.Vector(3.7352, -20.6651, 0)
	P157 = App.Vector(5.0910, -20.9012, 0)
	S093 = Part.Arc(P155, P156, P157)
	P158 = App.Vector(6.7029, -21.8318, 0)
	S094 = Part.LineSegment(P157, P158)
	P159 = App.Vector(6.9006, -21.8960, 0)
	P160 = App.Vector(7.1074, -21.8743, 0)
	S095 = Part.Arc(P158, P159, P160)
	P161 = App.Vector(7.5812, -21.7146, 0)
	P162 = App.Vector(8.0515, -21.5447, 0)
	S096 = Part.Arc(P160, P161, P162)
	P163 = App.Vector(8.2269, -21.4330, 0)
	P164 = App.Vector(8.3416, -21.2596, 0)
	S097 = Part.Arc(P162, P163, P164)
	P165 = App.Vector(9.0241, -19.5280, 0)
	S098 = Part.LineSegment(P164, P165)
	P166 = App.Vector(9.9383, -18.4995, 0)
	P167 = App.Vector(11.3006, -18.3050, 0)
	S099 = Part.Arc(P165, P166, P167)
	P168 = App.Vector(13.1212, -18.6920, 0)
	S100 = Part.LineSegment(P167, P168)
	P169 = App.Vector(13.3291, -18.6920, 0)
	P170 = App.Vector(13.5191, -18.6074, 0)
	S101 = Part.Arc(P168, P169, P170)
	P171 = App.Vector(13.9204, -18.3091, 0)
	P172 = App.Vector(14.3151, -18.0022, 0)
	S102 = Part.Arc(P170, P171, P172)
	P173 = App.Vector(14.4474, -17.8418, 0)
	P174 = App.Vector(14.5030, -17.6414, 0)
	S103 = Part.Arc(P172, P173, P174)
	P175 = App.Vector(14.6169, -15.7836, 0)
	S104 = Part.LineSegment(P174, P175)
	P176 = App.Vector(15.1685, -14.5229, 0)
	P177 = App.Vector(16.4041, -13.9170, 0)
	S105 = Part.Arc(P175, P176, P177)
	P178 = App.Vector(18.2552, -13.7224, 0)
	S106 = Part.LineSegment(P177, P178)
	P179 = App.Vector(18.4529, -13.6582, 0)
	P180 = App.Vector(18.6074, -13.5191, 0)
	S107 = Part.Arc(P178, P179, P180)
	P181 = App.Vector(18.8969, -13.1114, 0)
	P182 = App.Vector(19.1774, -12.6975, 0)
	S108 = Part.Arc(P180, P181, P182)
	P183 = App.Vector(19.2537, -12.5040, 0)
	P184 = App.Vector(19.2446, -12.2963, 0)
	S109 = Part.Arc(P182, P183, P184)
	P185 = App.Vector(18.7789, -10.4942, 0)
	S110 = Part.LineSegment(P184, P185)
	P186 = App.Vector(18.9140, -9.1248, 0)
	P187 = App.Vector(19.9018, -8.1667, 0)
	S111 = Part.Arc(P185, P186, P187)
	P188 = App.Vector(21.6021, -7.4097, 0)
	S112 = Part.LineSegment(P187, P188)
	P189 = App.Vector(21.7703, -7.2874, 0)
	P190 = App.Vector(21.8743, -7.1074, 0)
	S113 = Part.Arc(P188, P189, P190)
	P191 = App.Vector(22.0236, -6.6302, 0)
	P192 = App.Vector(22.1626, -6.1498, 0)
	S114 = Part.Arc(P190, P191, P192)
	P193 = App.Vector(22.1753, -5.9423, 0)
	P194 = App.Vector(22.1025, -5.7476, 0)
	S115 = Part.Arc(P192, P193, P194)
	P195 = App.Vector(21.1027, -4.1776, 0)
	S116 = Part.LineSegment(P194, P195)
	P196 = App.Vector(20.8080, -2.8334, 0)
	P197 = App.Vector(21.4514, -1.6170, 0)
	S117 = Part.Arc(P195, P196, P197)
	P198 = App.Vector(22.8346, -0.3716, 0)
	S118 = Part.LineSegment(P197, P198)
	P199 = App.Vector(22.9568, -0.2034, 0)
	P200 = App.Vector(23.0000, -0.0000, 0)
	S119 = Part.Arc(P198, P199, P200)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095, S096, S097, S098, S099, S100, S101, S102, S103, S104, S105, S106, S107, S108, S109, S110, S111, S112, S113, S114, S115, S116, S117, S118, S119])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(23.9943, 0.5217, 0)
	P002 = App.Vector(23.9773, 1.0432, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(23.8212, 1.6471, 0)
	P004 = App.Vector(23.4330, 2.1353, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(21.9970, 3.3195, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(21.6492, 3.9131, 0)
	P007 = App.Vector(21.7672, 4.5910, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(22.6978, 6.2029, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(22.8906, 6.7961, 0)
	P010 = App.Vector(22.8254, 7.4164, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(22.6587, 7.9109, 0)
	P012 = App.Vector(22.4814, 8.4016, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(22.1464, 8.9277, 0)
	P014 = App.Vector(21.6263, 9.2720, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(19.8947, 9.9545, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(19.3804, 10.4116, 0)
	P017 = App.Vector(19.2832, 11.0927, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(19.6701, 12.9133, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(19.6701, 13.5370, 0)
	P020 = App.Vector(19.4164, 14.1068, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(19.1051, 14.5256, 0)
	P022 = App.Vector(18.7849, 14.9375, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(18.3036, 15.3343, 0)
	P024 = App.Vector(17.7026, 15.5011, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(15.8448, 15.6150, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(15.2145, 15.8909, 0)
	P027 = App.Vector(14.9115, 16.5086, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(14.7169, 18.3597, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(14.5242, 18.9529, 0)
	P030 = App.Vector(14.1068, 19.4164, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(13.6814, 19.7185, 0)
	P032 = App.Vector(13.2495, 20.0113, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(12.6692, 20.2399, 0)
	P034 = App.Vector(12.0461, 20.2128, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(10.2440, 19.7471, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(9.5593, 19.8146, 0)
	P037 = App.Vector(9.0803, 20.3085, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(8.3232, 22.0089, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(7.9566, 22.5135, 0)
	P040 = App.Vector(7.4164, 22.8254, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(6.9185, 22.9812, 0)
	P042 = App.Vector(6.4172, 23.1262, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(5.7947, 23.1643, 0)
	P044 = App.Vector(5.2104, 22.9460, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(3.6405, 21.9462, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(2.9684, 21.7988, 0)
	P047 = App.Vector(2.3602, 22.1205, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(1.1147, 23.5037, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(0.6101, 23.8703, 0)
	P050 = App.Vector(0.0000, 24.0000, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-0.5217, 23.9943, 0)
	P052 = App.Vector(-1.0432, 23.9773, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-1.6471, 23.8212, 0)
	P054 = App.Vector(-2.1353, 23.4330, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-3.3195, 21.9970, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-3.9131, 21.6492, 0)
	P057 = App.Vector(-4.5910, 21.7672, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-6.2029, 22.6978, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-6.7961, 22.8906, 0)
	P060 = App.Vector(-7.4164, 22.8254, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-7.9109, 22.6587, 0)
	P062 = App.Vector(-8.4016, 22.4814, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-8.9277, 22.1464, 0)
	P064 = App.Vector(-9.2720, 21.6263, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-9.9545, 19.8947, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-10.4116, 19.3804, 0)
	P067 = App.Vector(-11.0927, 19.2832, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-12.9133, 19.6701, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-13.5370, 19.6701, 0)
	P070 = App.Vector(-14.1068, 19.4164, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-14.5256, 19.1051, 0)
	P072 = App.Vector(-14.9375, 18.7849, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-15.3343, 18.3036, 0)
	P074 = App.Vector(-15.5011, 17.7026, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-15.6150, 15.8448, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-15.8909, 15.2145, 0)
	P077 = App.Vector(-16.5086, 14.9115, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-18.3597, 14.7169, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-18.9529, 14.5242, 0)
	P080 = App.Vector(-19.4164, 14.1068, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-19.7185, 13.6814, 0)
	P082 = App.Vector(-20.0113, 13.2495, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-20.2399, 12.6692, 0)
	P084 = App.Vector(-20.2128, 12.0461, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-19.7471, 10.2440, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-19.8146, 9.5593, 0)
	P087 = App.Vector(-20.3085, 9.0803, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-22.0089, 8.3232, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-22.5135, 7.9566, 0)
	P090 = App.Vector(-22.8254, 7.4164, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-22.9812, 6.9185, 0)
	P092 = App.Vector(-23.1262, 6.4172, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-23.1643, 5.7947, 0)
	P094 = App.Vector(-22.9460, 5.2104, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-21.9462, 3.6405, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-21.7988, 2.9684, 0)
	P097 = App.Vector(-22.1205, 2.3602, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-23.5037, 1.1147, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-23.8703, 0.6101, 0)
	P100 = App.Vector(-24.0000, 0.0000, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-23.9943, -0.5217, 0)
	P102 = App.Vector(-23.9773, -1.0432, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-23.8212, -1.6471, 0)
	P104 = App.Vector(-23.4330, -2.1353, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-21.9970, -3.3195, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(-21.6492, -3.9131, 0)
	P107 = App.Vector(-21.7672, -4.5910, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(-22.6978, -6.2029, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(-22.8906, -6.7961, 0)
	P110 = App.Vector(-22.8254, -7.4164, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(-22.6587, -7.9109, 0)
	P112 = App.Vector(-22.4814, -8.4016, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(-22.1464, -8.9277, 0)
	P114 = App.Vector(-21.6263, -9.2720, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(-19.8947, -9.9545, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(-19.3804, -10.4116, 0)
	P117 = App.Vector(-19.2832, -11.0927, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(-19.6701, -12.9133, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(-19.6701, -13.5370, 0)
	P120 = App.Vector(-19.4164, -14.1068, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(-19.1051, -14.5256, 0)
	P122 = App.Vector(-18.7849, -14.9375, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(-18.3036, -15.3343, 0)
	P124 = App.Vector(-17.7026, -15.5011, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(-15.8448, -15.6150, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(-15.2145, -15.8909, 0)
	P127 = App.Vector(-14.9115, -16.5086, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(-14.7169, -18.3597, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(-14.5242, -18.9529, 0)
	P130 = App.Vector(-14.1068, -19.4164, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(-13.6814, -19.7185, 0)
	P132 = App.Vector(-13.2495, -20.0113, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(-12.6692, -20.2399, 0)
	P134 = App.Vector(-12.0461, -20.2128, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(-10.2440, -19.7471, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(-9.5593, -19.8146, 0)
	P137 = App.Vector(-9.0803, -20.3085, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(-8.3232, -22.0089, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(-7.9566, -22.5135, 0)
	P140 = App.Vector(-7.4164, -22.8254, 0)
	S083 = Part.Arc(P138, P139, P140)
	P141 = App.Vector(-6.9185, -22.9812, 0)
	P142 = App.Vector(-6.4172, -23.1262, 0)
	S084 = Part.Arc(P140, P141, P142)
	P143 = App.Vector(-5.7947, -23.1643, 0)
	P144 = App.Vector(-5.2104, -22.9460, 0)
	S085 = Part.Arc(P142, P143, P144)
	P145 = App.Vector(-3.6405, -21.9462, 0)
	S086 = Part.LineSegment(P144, P145)
	P146 = App.Vector(-2.9684, -21.7988, 0)
	P147 = App.Vector(-2.3602, -22.1205, 0)
	S087 = Part.Arc(P145, P146, P147)
	P148 = App.Vector(-1.1147, -23.5037, 0)
	S088 = Part.LineSegment(P147, P148)
	P149 = App.Vector(-0.6101, -23.8703, 0)
	P150 = App.Vector(-0.0000, -24.0000, 0)
	S089 = Part.Arc(P148, P149, P150)
	P151 = App.Vector(0.5217, -23.9943, 0)
	P152 = App.Vector(1.0432, -23.9773, 0)
	S090 = Part.Arc(P150, P151, P152)
	P153 = App.Vector(1.6471, -23.8212, 0)
	P154 = App.Vector(2.1353, -23.4330, 0)
	S091 = Part.Arc(P152, P153, P154)
	P155 = App.Vector(3.3195, -21.9970, 0)
	S092 = Part.LineSegment(P154, P155)
	P156 = App.Vector(3.9131, -21.6492, 0)
	P157 = App.Vector(4.5910, -21.7672, 0)
	S093 = Part.Arc(P155, P156, P157)
	P158 = App.Vector(6.2029, -22.6978, 0)
	S094 = Part.LineSegment(P157, P158)
	P159 = App.Vector(6.7961, -22.8906, 0)
	P160 = App.Vector(7.4164, -22.8254, 0)
	S095 = Part.Arc(P158, P159, P160)
	P161 = App.Vector(7.9109, -22.6587, 0)
	P162 = App.Vector(8.4016, -22.4814, 0)
	S096 = Part.Arc(P160, P161, P162)
	P163 = App.Vector(8.9277, -22.1464, 0)
	P164 = App.Vector(9.2720, -21.6263, 0)
	S097 = Part.Arc(P162, P163, P164)
	P165 = App.Vector(9.9545, -19.8947, 0)
	S098 = Part.LineSegment(P164, P165)
	P166 = App.Vector(10.4116, -19.3804, 0)
	P167 = App.Vector(11.0927, -19.2832, 0)
	S099 = Part.Arc(P165, P166, P167)
	P168 = App.Vector(12.9133, -19.6701, 0)
	S100 = Part.LineSegment(P167, P168)
	P169 = App.Vector(13.5370, -19.6701, 0)
	P170 = App.Vector(14.1068, -19.4164, 0)
	S101 = Part.Arc(P168, P169, P170)
	P171 = App.Vector(14.5256, -19.1051, 0)
	P172 = App.Vector(14.9375, -18.7849, 0)
	S102 = Part.Arc(P170, P171, P172)
	P173 = App.Vector(15.3343, -18.3036, 0)
	P174 = App.Vector(15.5011, -17.7026, 0)
	S103 = Part.Arc(P172, P173, P174)
	P175 = App.Vector(15.6150, -15.8448, 0)
	S104 = Part.LineSegment(P174, P175)
	P176 = App.Vector(15.8909, -15.2145, 0)
	P177 = App.Vector(16.5086, -14.9115, 0)
	S105 = Part.Arc(P175, P176, P177)
	P178 = App.Vector(18.3597, -14.7169, 0)
	S106 = Part.LineSegment(P177, P178)
	P179 = App.Vector(18.9529, -14.5242, 0)
	P180 = App.Vector(19.4164, -14.1068, 0)
	S107 = Part.Arc(P178, P179, P180)
	P181 = App.Vector(19.7185, -13.6814, 0)
	P182 = App.Vector(20.0113, -13.2495, 0)
	S108 = Part.Arc(P180, P181, P182)
	P183 = App.Vector(20.2399, -12.6692, 0)
	P184 = App.Vector(20.2128, -12.0461, 0)
	S109 = Part.Arc(P182, P183, P184)
	P185 = App.Vector(19.7471, -10.2440, 0)
	S110 = Part.LineSegment(P184, P185)
	P186 = App.Vector(19.8146, -9.5593, 0)
	P187 = App.Vector(20.3085, -9.0803, 0)
	S111 = Part.Arc(P185, P186, P187)
	P188 = App.Vector(22.0089, -8.3232, 0)
	S112 = Part.LineSegment(P187, P188)
	P189 = App.Vector(22.5135, -7.9566, 0)
	P190 = App.Vector(22.8254, -7.4164, 0)
	S113 = Part.Arc(P188, P189, P190)
	P191 = App.Vector(22.9812, -6.9185, 0)
	P192 = App.Vector(23.1262, -6.4172, 0)
	S114 = Part.Arc(P190, P191, P192)
	P193 = App.Vector(23.1643, -5.7947, 0)
	P194 = App.Vector(22.9460, -5.2104, 0)
	S115 = Part.Arc(P192, P193, P194)
	P195 = App.Vector(21.9462, -3.6405, 0)
	S116 = Part.LineSegment(P194, P195)
	P196 = App.Vector(21.7988, -2.9684, 0)
	P197 = App.Vector(22.1205, -2.3602, 0)
	S117 = Part.Arc(P195, P196, P197)
	P198 = App.Vector(23.5037, -1.1147, 0)
	S118 = Part.LineSegment(P197, P198)
	P199 = App.Vector(23.8703, -0.6101, 0)
	P200 = App.Vector(24.0000, -0.0000, 0)
	S119 = Part.Arc(P198, P199, P200)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083, S084, S085, S086, S087, S088, S089, S090, S091, S092, S093, S094, S095, S096, S097, S098, S099, S100, S101, S102, S103, S104, S105, S106, S107, S108, S109, S110, S111, S112, S113, S114, S115, S116, S117, S118, S119])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceTopWave_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopWave():
	FA000 = face_reinforced_tube_faceTopWave_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def reinforced_tube_faceTopInt():
	rOneFig = undefined
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-25.0000, 0.0000, 0)
	P001 = App.Vector(-24.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-24.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-25.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa0():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa1_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(25.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(24.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(24.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa1():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceSide():
	FA000 = face_reinforced_tube_faceSide_Fa0()
	FA001 = face_reinforced_tube_faceSide_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def fex_subpax_reinforced_tube_topExt():
	FIG = reinforced_tube_faceTopExt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topExt = fex_subpax_reinforced_tube_topExt()

def fex_subpax_reinforced_tube_topWave():
	FIG = reinforced_tube_faceTopWave()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topWave = fex_subpax_reinforced_tube_topWave()

pax_reinforced_tube = subpax_reinforced_tube_topExt.fuse([subpax_reinforced_tube_topWave])

pax_reinforced_tube.check()
#pax_reinforced_tube.exportBrep(f"{outFileName}.brep")
#pax_reinforced_tube.exportIges(f"{outFileName}.igs")
#pax_reinforced_tube.exportStep(f"{outFileName}.stp")
pax_reinforced_tube.exportStl(f"{outFileName}.stl")

