# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "reinforced_tube"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(25.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(24.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopExt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopExt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopExt():
	FA000 = face_reinforced_tube_faceTopExt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(23.9758, 1.0768, 0)
	P002 = App.Vector(23.9034, 2.1513, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(22.7034, 3.7939, 0)
	P004 = App.Vector(20.6898, 3.5050, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(20.3765, 3.2496, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(16.3874, 4.5226, 0)
	P007 = App.Vector(19.1589, 7.6614, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(19.5588, 7.6030, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(21.4356, 8.3877, 0)
	P010 = App.Vector(21.6233, 10.4132, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(21.1343, 11.3728, 0)
	P012 = App.Vector(20.6028, 12.3096, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(18.8089, 13.2688, 0)
	P014 = App.Vector(17.1201, 12.1348, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(16.9486, 11.7688, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(12.8022, 11.1850, 0)
	P017 = App.Vector(13.9374, 15.2154, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(14.3231, 15.3363, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(15.6735, 16.8576, 0)
	P020 = App.Vector(14.9638, 18.7640, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(14.1068, 19.4164, 0)
	P022 = App.Vector(13.2215, 20.0298, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(11.1891, 20.1157, 0)
	P024 = App.Vector(10.1596, 18.3613, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(10.1639, 17.9571, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(6.6814, 15.6320, 0)
	P027 = App.Vector(5.9554, 19.7558, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(6.2505, 20.0321, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(6.8071, 21.9887, 0)
	P030 = App.Vector(5.3405, 23.3983, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(4.2854, 23.6143, 0)
	P032 = App.Vector(3.2216, 23.7828, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(1.3532, 22.9784, 0)
	P034 = App.Vector(1.1868, 20.9510, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(1.3660, 20.5887, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-0.7627, 16.9829, 0)
	P037 = App.Vector(-3.2061, 20.3833, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-3.0601, 20.7603, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-3.4075, 22.7646, 0)
	P040 = App.Vector(-5.3405, 23.3983, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-6.3849, 23.1351, 0)
	P042 = App.Vector(-7.4164, 22.8254, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-8.7508, 21.2900, 0)
	P044 = App.Vector(-8.0210, 19.3912, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-7.7023, 19.1425, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-8.0558, 14.9701, 0)
	P047 = App.Vector(-11.7326, 16.9737, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-11.7646, 17.3766, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-12.9473, 19.0317, 0)
	P050 = App.Vector(-14.9638, 18.7640, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-15.7905, 18.0737, 0)
	P052 = App.Vector(-16.5855, 17.3471, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-17.1215, 15.3848, 0)
	P054 = App.Vector(-15.6402, 13.9906, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-15.2452, 13.9048, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-13.7533, 9.9923, 0)
	P057 = App.Vector(-17.9353, 10.2022, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-18.1390, 10.5514, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-19.9226, 11.5294, 0)
	P060 = App.Vector(-21.6233, 10.4132, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-22.0687, 9.4326, 0)
	P062 = App.Vector(-22.4696, 8.4330, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-22.1012, 6.4325, 0)
	P064 = App.Vector(-20.1616, 5.8191, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-19.7685, 5.9132, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-16.7268, 3.0355, 0)
	P067 = App.Vector(-20.5857, 1.4100, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-20.9207, 1.6362, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-22.9521, 1.7435, 0)
	P070 = App.Vector(-24.0000, 0.0000, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-23.9758, -1.0768, 0)
	P072 = App.Vector(-23.9034, -2.1513, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-22.7034, -3.7939, 0)
	P074 = App.Vector(-20.6898, -3.5050, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-20.3765, -3.2496, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-16.3874, -4.5226, 0)
	P077 = App.Vector(-19.1589, -7.6614, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-19.5588, -7.6030, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-21.4356, -8.3877, 0)
	P080 = App.Vector(-21.6233, -10.4132, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-21.1343, -11.3728, 0)
	P082 = App.Vector(-20.6028, -12.3096, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-18.8089, -13.2688, 0)
	P084 = App.Vector(-17.1201, -12.1348, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-16.9486, -11.7688, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-12.8022, -11.1850, 0)
	P087 = App.Vector(-13.9374, -15.2154, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-14.3231, -15.3363, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-15.6735, -16.8576, 0)
	P090 = App.Vector(-14.9638, -18.7640, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-14.1068, -19.4164, 0)
	P092 = App.Vector(-13.2215, -20.0298, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-11.1891, -20.1157, 0)
	P094 = App.Vector(-10.1596, -18.3613, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-10.1639, -17.9571, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-6.6814, -15.6320, 0)
	P097 = App.Vector(-5.9554, -19.7558, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-6.2505, -20.0321, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-6.8071, -21.9887, 0)
	P100 = App.Vector(-5.3405, -23.3983, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-4.2854, -23.6143, 0)
	P102 = App.Vector(-3.2216, -23.7828, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-1.3532, -22.9784, 0)
	P104 = App.Vector(-1.1868, -20.9510, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-1.3660, -20.5887, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(0.7627, -16.9829, 0)
	P107 = App.Vector(3.2061, -20.3833, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(3.0601, -20.7603, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(3.4075, -22.7646, 0)
	P110 = App.Vector(5.3405, -23.3983, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(6.3849, -23.1351, 0)
	P112 = App.Vector(7.4164, -22.8254, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(8.7508, -21.2900, 0)
	P114 = App.Vector(8.0210, -19.3912, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(7.7023, -19.1425, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(8.0558, -14.9701, 0)
	P117 = App.Vector(11.7326, -16.9737, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(11.7646, -17.3766, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(12.9473, -19.0317, 0)
	P120 = App.Vector(14.9638, -18.7640, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(15.7905, -18.0737, 0)
	P122 = App.Vector(16.5855, -17.3471, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(17.1215, -15.3848, 0)
	P124 = App.Vector(15.6402, -13.9906, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(15.2452, -13.9048, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(13.7533, -9.9923, 0)
	P127 = App.Vector(17.9353, -10.2022, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(18.1390, -10.5514, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(19.9226, -11.5294, 0)
	P130 = App.Vector(21.6233, -10.4132, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(22.0687, -9.4326, 0)
	P132 = App.Vector(22.4696, -8.4330, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(22.1012, -6.4325, 0)
	P134 = App.Vector(20.1616, -5.8191, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(19.7685, -5.9132, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(16.7268, -3.0355, 0)
	P137 = App.Vector(20.5857, -1.4100, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(20.9207, -1.6362, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(22.9521, -1.7435, 0)
	P140 = App.Vector(24.0000, -0.0000, 0)
	S083 = Part.Arc(P138, P139, P140)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1():
	P000 = App.Vector(23.0000, 0.0000, 0)
	P001 = App.Vector(22.9768, 1.0319, 0)
	P002 = App.Vector(22.9074, 2.0617, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(22.3152, 2.8723, 0)
	P004 = App.Vector(21.3215, 2.7297, 0)
	S001 = Part.Arc(P002, P003, P004)
	P005 = App.Vector(21.0081, 2.4744, 0)
	S002 = Part.LineSegment(P004, P005)
	P006 = App.Vector(15.4234, 4.2566, 0)
	P007 = App.Vector(19.3035, 8.6509, 0)
	S003 = Part.Arc(P005, P006, P007)
	P008 = App.Vector(19.7035, 8.5924, 0)
	S004 = Part.LineSegment(P007, P008)
	P009 = App.Vector(20.6297, 8.9797, 0)
	P010 = App.Vector(20.7223, 9.9793, 0)
	S005 = Part.Arc(P008, P009, P010)
	P011 = App.Vector(20.2537, 10.8990, 0)
	P012 = App.Vector(19.7443, 11.7967, 0)
	S006 = Part.Arc(P010, P011, P012)
	P013 = App.Vector(18.8591, 12.2701, 0)
	P014 = App.Vector(18.0256, 11.7104, 0)
	S007 = Part.Arc(P012, P013, P014)
	P015 = App.Vector(17.8541, 11.3444, 0)
	S008 = Part.LineSegment(P014, P015)
	P016 = App.Vector(12.0491, 10.5270, 0)
	P017 = App.Vector(13.6384, 16.1697, 0)
	S009 = Part.Arc(P015, P016, P017)
	P018 = App.Vector(14.0241, 16.2906, 0)
	S010 = Part.LineSegment(P017, P018)
	P019 = App.Vector(14.6905, 17.0413, 0)
	P020 = App.Vector(14.3403, 17.9821, 0)
	S011 = Part.Arc(P018, P019, P020)
	P021 = App.Vector(13.5191, 18.6074, 0)
	P022 = App.Vector(12.6706, 19.1952, 0)
	S012 = Part.Arc(P020, P021, P022)
	P023 = App.Vector(11.6676, 19.2376, 0)
	P024 = App.Vector(11.1595, 18.3718, 0)
	S013 = Part.Arc(P022, P023, P024)
	P025 = App.Vector(11.1638, 17.9676, 0)
	S014 = Part.LineSegment(P024, P025)
	P026 = App.Vector(6.2884, 14.7124, 0)
	P027 = App.Vector(5.2720, 20.4858, 0)
	S015 = Part.Arc(P025, P026, P027)
	P028 = App.Vector(5.5671, 20.7621, 0)
	S016 = Part.LineSegment(P027, P028)
	P029 = App.Vector(5.8418, 21.7277, 0)
	P030 = App.Vector(5.1180, 22.4233, 0)
	S017 = Part.Arc(P028, P029, P030)
	P031 = App.Vector(4.1068, 22.6304, 0)
	P032 = App.Vector(3.0874, 22.7918, 0)
	S018 = Part.Arc(P030, P031, P032)
	P033 = App.Vector(2.1653, 22.3949, 0)
	P034 = App.Vector(2.0832, 21.3943, 0)
	S019 = Part.Arc(P032, P033, P034)
	P035 = App.Vector(2.2624, 21.0320, 0)
	S020 = Part.LineSegment(P034, P035)
	P036 = App.Vector(-0.7178, 15.9839, 0)
	P037 = App.Vector(-4.1386, 20.7445, 0)
	S021 = Part.Arc(P035, P036, P037)
	P038 = App.Vector(-3.9926, 21.1215, 0)
	S022 = Part.LineSegment(P037, P038)
	P039 = App.Vector(-4.1640, 22.1106, 0)
	P040 = App.Vector(-5.1180, 22.4233, 0)
	S023 = Part.Arc(P038, P039, P040)
	P041 = App.Vector(-6.1188, 22.1711, 0)
	P042 = App.Vector(-7.1074, 21.8743, 0)
	S024 = Part.Arc(P040, P041, P042)
	P043 = App.Vector(-7.7659, 21.1166, 0)
	P044 = App.Vector(-7.4058, 20.1795, 0)
	S025 = Part.Arc(P042, P043, P044)
	P045 = App.Vector(-7.0871, 19.9308, 0)
	S026 = Part.LineSegment(P044, P045)
	P046 = App.Vector(-7.5819, 14.0895, 0)
	P047 = App.Vector(-12.7295, 16.8945, 0)
	S027 = Part.Arc(P045, P046, P047)
	P048 = App.Vector(-12.7615, 17.2975, 0)
	S028 = Part.LineSegment(P047, P048)
	P049 = App.Vector(-13.3451, 18.1143, 0)
	P050 = App.Vector(-14.3403, 17.9821, 0)
	S029 = Part.Arc(P048, P049, P050)
	P051 = App.Vector(-15.1326, 17.3206, 0)
	P052 = App.Vector(-15.8944, 16.6243, 0)
	S030 = Part.Arc(P050, P051, P052)
	P053 = App.Vector(-16.1590, 15.6559, 0)
	P054 = App.Vector(-15.4279, 14.9679, 0)
	S031 = Part.Arc(P052, P053, P054)
	P055 = App.Vector(-15.0329, 14.8821, 0)
	S032 = Part.LineSegment(P054, P055)
	P056 = App.Vector(-12.9443, 9.4046, 0)
	P057 = App.Vector(-18.7991, 9.6983, 0)
	S033 = Part.Arc(P055, P056, P057)
	P058 = App.Vector(-19.0028, 10.0475, 0)
	S034 = Part.LineSegment(P057, P058)
	P059 = App.Vector(-19.8830, 10.5302, 0)
	P060 = App.Vector(-20.7223, 9.9793, 0)
	S035 = Part.Arc(P058, P059, P060)
	P061 = App.Vector(-21.1491, 9.0396, 0)
	P062 = App.Vector(-21.5334, 8.0816, 0)
	S036 = Part.Arc(P060, P061, P062)
	P063 = App.Vector(-21.3516, 7.0943, 0)
	P064 = App.Vector(-20.3944, 6.7917, 0)
	S037 = Part.Arc(P062, P063, P064)
	P065 = App.Vector(-20.0013, 6.8857, 0)
	S038 = Part.LineSegment(P064, P065)
	P066 = App.Vector(-15.7429, 2.8569, 0)
	P067 = App.Vector(-21.1453, 0.5813, 0)
	S039 = Part.Arc(P065, P066, P067)
	P068 = App.Vector(-21.4803, 0.8075, 0)
	S040 = Part.LineSegment(P067, P068)
	P069 = App.Vector(-22.4828, 0.8604, 0)
	P070 = App.Vector(-23.0000, 0.0000, 0)
	S041 = Part.Arc(P068, P069, P070)
	P071 = App.Vector(-22.9768, -1.0319, 0)
	P072 = App.Vector(-22.9074, -2.0617, 0)
	S042 = Part.Arc(P070, P071, P072)
	P073 = App.Vector(-22.3152, -2.8723, 0)
	P074 = App.Vector(-21.3215, -2.7297, 0)
	S043 = Part.Arc(P072, P073, P074)
	P075 = App.Vector(-21.0081, -2.4744, 0)
	S044 = Part.LineSegment(P074, P075)
	P076 = App.Vector(-15.4234, -4.2566, 0)
	P077 = App.Vector(-19.3035, -8.6509, 0)
	S045 = Part.Arc(P075, P076, P077)
	P078 = App.Vector(-19.7035, -8.5924, 0)
	S046 = Part.LineSegment(P077, P078)
	P079 = App.Vector(-20.6297, -8.9797, 0)
	P080 = App.Vector(-20.7223, -9.9793, 0)
	S047 = Part.Arc(P078, P079, P080)
	P081 = App.Vector(-20.2537, -10.8990, 0)
	P082 = App.Vector(-19.7443, -11.7967, 0)
	S048 = Part.Arc(P080, P081, P082)
	P083 = App.Vector(-18.8591, -12.2701, 0)
	P084 = App.Vector(-18.0256, -11.7104, 0)
	S049 = Part.Arc(P082, P083, P084)
	P085 = App.Vector(-17.8541, -11.3444, 0)
	S050 = Part.LineSegment(P084, P085)
	P086 = App.Vector(-12.0491, -10.5270, 0)
	P087 = App.Vector(-13.6384, -16.1697, 0)
	S051 = Part.Arc(P085, P086, P087)
	P088 = App.Vector(-14.0241, -16.2906, 0)
	S052 = Part.LineSegment(P087, P088)
	P089 = App.Vector(-14.6905, -17.0413, 0)
	P090 = App.Vector(-14.3403, -17.9821, 0)
	S053 = Part.Arc(P088, P089, P090)
	P091 = App.Vector(-13.5191, -18.6074, 0)
	P092 = App.Vector(-12.6706, -19.1952, 0)
	S054 = Part.Arc(P090, P091, P092)
	P093 = App.Vector(-11.6676, -19.2376, 0)
	P094 = App.Vector(-11.1595, -18.3718, 0)
	S055 = Part.Arc(P092, P093, P094)
	P095 = App.Vector(-11.1638, -17.9676, 0)
	S056 = Part.LineSegment(P094, P095)
	P096 = App.Vector(-6.2884, -14.7124, 0)
	P097 = App.Vector(-5.2720, -20.4858, 0)
	S057 = Part.Arc(P095, P096, P097)
	P098 = App.Vector(-5.5671, -20.7621, 0)
	S058 = Part.LineSegment(P097, P098)
	P099 = App.Vector(-5.8418, -21.7277, 0)
	P100 = App.Vector(-5.1180, -22.4233, 0)
	S059 = Part.Arc(P098, P099, P100)
	P101 = App.Vector(-4.1068, -22.6304, 0)
	P102 = App.Vector(-3.0874, -22.7918, 0)
	S060 = Part.Arc(P100, P101, P102)
	P103 = App.Vector(-2.1653, -22.3949, 0)
	P104 = App.Vector(-2.0832, -21.3943, 0)
	S061 = Part.Arc(P102, P103, P104)
	P105 = App.Vector(-2.2624, -21.0320, 0)
	S062 = Part.LineSegment(P104, P105)
	P106 = App.Vector(0.7178, -15.9839, 0)
	P107 = App.Vector(4.1386, -20.7445, 0)
	S063 = Part.Arc(P105, P106, P107)
	P108 = App.Vector(3.9926, -21.1215, 0)
	S064 = Part.LineSegment(P107, P108)
	P109 = App.Vector(4.1640, -22.1106, 0)
	P110 = App.Vector(5.1180, -22.4233, 0)
	S065 = Part.Arc(P108, P109, P110)
	P111 = App.Vector(6.1188, -22.1711, 0)
	P112 = App.Vector(7.1074, -21.8743, 0)
	S066 = Part.Arc(P110, P111, P112)
	P113 = App.Vector(7.7659, -21.1166, 0)
	P114 = App.Vector(7.4058, -20.1795, 0)
	S067 = Part.Arc(P112, P113, P114)
	P115 = App.Vector(7.0871, -19.9308, 0)
	S068 = Part.LineSegment(P114, P115)
	P116 = App.Vector(7.5819, -14.0895, 0)
	P117 = App.Vector(12.7295, -16.8945, 0)
	S069 = Part.Arc(P115, P116, P117)
	P118 = App.Vector(12.7615, -17.2975, 0)
	S070 = Part.LineSegment(P117, P118)
	P119 = App.Vector(13.3451, -18.1143, 0)
	P120 = App.Vector(14.3403, -17.9821, 0)
	S071 = Part.Arc(P118, P119, P120)
	P121 = App.Vector(15.1326, -17.3206, 0)
	P122 = App.Vector(15.8944, -16.6243, 0)
	S072 = Part.Arc(P120, P121, P122)
	P123 = App.Vector(16.1590, -15.6559, 0)
	P124 = App.Vector(15.4279, -14.9679, 0)
	S073 = Part.Arc(P122, P123, P124)
	P125 = App.Vector(15.0329, -14.8821, 0)
	S074 = Part.LineSegment(P124, P125)
	P126 = App.Vector(12.9443, -9.4046, 0)
	P127 = App.Vector(18.7991, -9.6983, 0)
	S075 = Part.Arc(P125, P126, P127)
	P128 = App.Vector(19.0028, -10.0475, 0)
	S076 = Part.LineSegment(P127, P128)
	P129 = App.Vector(19.8830, -10.5302, 0)
	P130 = App.Vector(20.7223, -9.9793, 0)
	S077 = Part.Arc(P128, P129, P130)
	P131 = App.Vector(21.1491, -9.0396, 0)
	P132 = App.Vector(21.5334, -8.0816, 0)
	S078 = Part.Arc(P130, P131, P132)
	P133 = App.Vector(21.3516, -7.0943, 0)
	P134 = App.Vector(20.3944, -6.7917, 0)
	S079 = Part.Arc(P132, P133, P134)
	P135 = App.Vector(20.0013, -6.8857, 0)
	S080 = Part.LineSegment(P134, P135)
	P136 = App.Vector(15.7429, -2.8569, 0)
	P137 = App.Vector(21.1453, -0.5813, 0)
	S081 = Part.Arc(P135, P136, P137)
	P138 = App.Vector(21.4803, -0.8075, 0)
	S082 = Part.LineSegment(P137, P138)
	P139 = App.Vector(22.4828, -0.8604, 0)
	P140 = App.Vector(23.0000, -0.0000, 0)
	S083 = Part.Arc(P138, P139, P140)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007, S008, S009, S010, S011, S012, S013, S014, S015, S016, S017, S018, S019, S020, S021, S022, S023, S024, S025, S026, S027, S028, S029, S030, S031, S032, S033, S034, S035, S036, S037, S038, S039, S040, S041, S042, S043, S044, S045, S046, S047, S048, S049, S050, S051, S052, S053, S054, S055, S056, S057, S058, S059, S060, S061, S062, S063, S064, S065, S066, S067, S068, S069, S070, S071, S072, S073, S074, S075, S076, S077, S078, S079, S080, S081, S082, S083])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceTopWave_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopWave_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopWave():
	FA000 = face_reinforced_tube_faceTopWave_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr0():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(16.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(15.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_reinforced_tube_faceTopInt_Fa0():
	FC000 = ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr0()
	FC001 = ctr_face_reinforced_tube_faceTopInt_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceTopInt():
	FA000 = face_reinforced_tube_faceTopInt_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_reinforced_tube_faceSide_Fa0_Ctr0():
	P000 = App.Vector(-25.0000, 0.0000, 0)
	P001 = App.Vector(-24.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-24.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-25.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-25.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa0():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa1_Ctr0():
	P000 = App.Vector(24.0000, 0.0000, 0)
	P001 = App.Vector(25.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(25.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(24.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(24.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa1():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa2_Ctr0():
	P000 = App.Vector(-16.0000, 0.0000, 0)
	P001 = App.Vector(-15.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-15.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-16.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-16.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa2():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_reinforced_tube_faceSide_Fa3_Ctr0():
	P000 = App.Vector(15.0000, 0.0000, 0)
	P001 = App.Vector(16.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(16.0000, 30.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(15.0000, 30.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(15.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_reinforced_tube_faceSide_Fa3():
	FC000 = ctr_face_reinforced_tube_faceSide_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def reinforced_tube_faceSide():
	FA000 = face_reinforced_tube_faceSide_Fa0()
	FA001 = face_reinforced_tube_faceSide_Fa1()
	FA002 = face_reinforced_tube_faceSide_Fa2()
	FA003 = face_reinforced_tube_faceSide_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def fex_subpax_reinforced_tube_topExt():
	FIG = reinforced_tube_faceTopExt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topExt = fex_subpax_reinforced_tube_topExt()

def fex_subpax_reinforced_tube_topWave():
	FIG = reinforced_tube_faceTopWave()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topWave = fex_subpax_reinforced_tube_topWave()

def fex_subpax_reinforced_tube_topInt():
	FIG = reinforced_tube_faceTopInt()
	VEX = FIG.extrude(App.Vector(0, 0, 30))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0)
	VFP = VR3.translate(App.Vector(0, 0, 0))
	return VFP
subpax_reinforced_tube_topInt = fex_subpax_reinforced_tube_topInt()

pax_reinforced_tube = subpax_reinforced_tube_topExt.fuse([subpax_reinforced_tube_topWave, subpax_reinforced_tube_topInt])

pax_reinforced_tube.check()
#pax_reinforced_tube.exportBrep(f"{outFileName}.brep")
#pax_reinforced_tube.exportIges(f"{outFileName}.igs")
#pax_reinforced_tube.exportStep(f"{outFileName}.stp")
pax_reinforced_tube.exportStl(f"{outFileName}.stl")

